config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]

  # **************************************************************************** #
  #  all routes must be defined above this line to avoid conflicts with :things  #
  # **************************************************************************** #

  resources :things, path: ''

  get 'home/index'
  root "home#index"
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  belongs_to :user

  default_scope -> { order('created_at DESC') }

  acts_as_url :name, :sync_url => true, :allow_duplicates => true

  paginates_per 18

  validates_presence_of :filekey, :url

  before_create :generate_url_key

  def file_url?
    filekey.present? && filename.present?
  end

  def file_url
    return nil unless file_url?
    "http://s3.amazonaws.com/#{S3_BUCKET}/things/#{filekey}/#{CGI.escape filename}"
  end

  def imgix_file_url
    return nil unless file_url?
    "http://#{ENV['IMGIX_ROOT_URL']}/things/#{filekey}/#{CGI.escape filename}"
  end

  def file_extension
    return nil unless filename.present?
    filename.rpartition(".")[2]
  end

  def file_is_image?
    return false unless file_url? && content_type.present?
    content_type.starts_with? "image/"
  end

  def name
    length = 50
    return "untitled" unless filename.present?
    return filename.slice(0,length).strip unless body.present?
    body.lines.first.strip.slice(0,length).strip
  end

  def generate_url_key
    begin
      self.url_key = SecureRandom.hex(3)
    end while Thing.exists?(:url_key => url_key)
  end

  def to_param
    "#{url}-#{url_key}"
  end

  class << self
    def from_param(param)
      find_by_url_key!(param.rpartition("-")[2])
    end

    def s3_policy(opts = {})
      Base64.encode64(
        { 
          expiration: 36.hours.from_now.utc.strftime('%Y-%m-%dT%H:%M:%S.000Z'),
          conditions: [
            { bucket: S3_BUCKET },
            ['starts-with', '$key', ''],
            ['starts-with', '$Content-Type', ''],
            { acl: 'public-read' }
          ]
        }.to_json
      ).gsub(/\n|\r/, '')
    end

    def s3_signature(opts = {})
      Base64.encode64(
        OpenSSL::HMAC.digest(
          OpenSSL::Digest::Digest.new('sha1'),
          ENV["AWS_SECRET_ACCESS_KEY"],
          s3_policy(secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"])
        )
      ).gsub(/\n/, '')
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :things
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  def index
    @things = Thing.all.page params[:page]
  end

  def show
    if @thing.to_param != params[:id]
      return redirect_to @thing, :status => :moved_permanently
    end
  end

  def new
    redirect_to things_path
  end

  def edit
  end

  def create
    @thing = current_user.things.new(thing_params.merge(body: params[:thing][:filename].rpartition(".")[0]))

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'CREATED' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'UPDATED' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      begin
        @thing = if ["show"].include?(action_name)
          Thing.from_param(params[:id])
        else
          current_user.things.from_param(params[:id])
        end
      rescue ActiveRecord::RecordNotFound
        redirect_to things_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:body, :filekey, :filename, :content_type, :featured)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Standard Creative</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <script type="text/javascript">var switchTo5x=true;</script>
    <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
    <script type="text/javascript">stLight.options({publisher: "4f2f019c-cb9c-4cbc-80f7-27bcf42752b5", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

    <%= csrf_meta_tags %>
</head>
<body>
    <p class="flash notice <%= "present" if notice.present? %>"><%= notice %></p>
    <p class="flash alert <%= "present" if alert.present? %>"><%= alert %></p>

    <%= yield %>
</body>
</html>

app/views/things/_dropzone.html.erb
<script>
    var AWS_ACCESS_KEY_ID = '<%=j ENV['AWS_ACCESS_KEY_ID'] %>';
    var S3_BUCKET = '<%=j S3_BUCKET %>';

    var THING_S3_POLICY = '<%=j Thing.s3_policy %>';
    var THING_S3_SIGNATURE = '<%=j Thing.s3_signature %>';

    var page_entity = <%== controller.render_to_string(template: 'things/show.json.jbuilder', locals: { thing: @thing }) %>
</script>

<div id="droparea" style="display:none;">
    <div class="instructions">
        DROP THINGS HERE
    </div>
</div>

<div id="progress" style="display:none;">
    <div class="uploads">
        <!--
        <div class="upload">
            <div class="filename">asdf.jpg</div>
            <div class="percent">20%</div>
        </div>
        -->
    </div>
</div>

app/views/things/_form.html.erb
<%= render "dropzone" %>

<%= form_for(@thing) do |f| %>
    <div class="row">
        <%= f.check_box :featured %>
        <%= f.label :featured %>
    </div>

    <div class="row">
        <%= f.label :body, class: "label" %>
        <%= f.text_area :body, class: "input" %>
    </div>

    <div class="row actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/things/_header.html.erb
<% class_name ||= "" %>

<div id="header" class="<%= class_name %>">
    <a class="logo" href="<%= things_path %>">Standard Creative</a>
    <a class="contact" href="mailto:ronen@ronenv.com">CONTACT</a>
</div>

app/views/things/edit.html.erb
<%= render "header", { class_name: "small" } %>

<%= render "form" %>

<% if user_signed_in? %>
    <div id="user_controls">
        <%= link_to 'Delete', @thing, method: :delete, class: "button", data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>

app/views/things/index.html.erb
<%= render "header" %>

<div id="things" class="grid">
    <% @things.each do |thing| %>
        <%= link_to thing, { class: "wrapper" } do %>
            <div class="thing" data-content-type="<%= thing.content_type %>">
                <div class="center_within">
                    <% if thing.file_is_image? %>
                        <img class="image" src="<%= thing.imgix_file_url %>?w=280&amp;h=280">
                    <% else %>
                        <div class="unknown">
                            <%= thing.name %>
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

<%= paginate @things %>

<% if user_signed_in? %>
    <%= render "dropzone" %>
<% end %>

app/views/things/show.html.erb
<%= render "header", { class_name: "small" } %>

<% if @thing.file_url? %>
    <div id="thing">
        <% if @thing.file_is_image? %>
            <img class="image max_default" src="<%= @thing.file_url %>">
        <% else %>
            <a class="download" href="<%= @thing.file_url %>" target="_blank">Download <%= @thing.file_extension %></a>
        <% end %>

        <% if @thing.body? %>
            <div class="body">
                <%= simple_format @thing.body %>
            </div>
        <% end %>
    </div>
<% end %>

<div id="share_buttons">
    <a class="share_toggle" href="<% link_to @thing %>">SHARE</a>

    <div id="share_services" style="display:none;">
        <span class="st_twitter_large" displayText="Tweet"></span>
        <span class="st_facebook_large" displayText="Facebook"></span>
        <span class="st_tumblr_large" displayText="Tumblr"></span>
        <span class="st_reddit_large" displayText="Reddit"></span>
        <span class="st_email_large" displayText="Email"></span>
    </div>
</div>

<% if user_signed_in? %>
    <div id="user_controls">
        <%= link_to 'Edit', edit_thing_path(@thing), class: "button" %>
    </div>
<% end %>